#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI2YaGKsOz3SC/bd+Z3xxD+KImfdPkpkOBFyg3oHmSbPhYt7MvdXv4AMZljRXK8UpaKGiBraTRZdwsmH2QlSxVoUdNssKH+EW0Z1BioN+Xmc89KnrSfWDOOfvPlBv+kxsB4+qZc92wZUuGwOtTjaWLlLEd/NlBN+ERJxMHA8vh0SSVzvZcFcyLE31eeeOEtHjSCGGFaii+bSHStmRn5MWib1W6fuTxIPVPDTuUo3DeBhKSnG1z9rPXl4IIKDDPMxGIHgg3CTdXkwFxKFaWBYYRN4/mACNCBIjI6240n9RLdj2XQXgWsubP4n0ha9hugm6nGMpW8+1bzlKolUFk1G7r jfbrown@core
coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/c8f400502b19f964e7c768e22e749e73
    # multi-region deployments, multi-cloud deployments, and droplets without
    # private networking need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4   # used for fleetctl ssh command
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
